import type { SampleProfile } from '../types/npc';

export const SAMPLE_PROFILES: Record<'idle' | 'looping' | 'protagonist', SampleProfile> = {
  idle: {
    id: 'sample-idle',
    name: 'Sample 01: The Still Sentinel',
    tagline: 'Waiting for player interaction since 2011',
    npcType: 'IDLE NPC',
    npcLevel: 'HIGH LEVEL NPC',
    targetScore: 94,
    metrics: {
      movementRandomness: 8,
      pathRepetition: 92,
      idleBehavior: 96,
      directionChanges: 14,
      activityLevel: 12,
      movementRepetition: 88,
      predictability: 95,
      loopDetected: true,
    },
    observations: [
      'Subject stayed stationary for 96% of the tracking window.',
      'Movement pattern resembles an idle vendor waiting for dialogue input.',
      'Only micro-sways detected; likely rendering standard breathing cycle.',
      'Randomness levels are dangerously low for an organic human.',
      'System concluded subject could be replaced by a cardboard cutout.',
    ],
    mainCharacterReason: 'Insufficient kinetic variance. Protagonists rarely stay this still unless AFK.',
    description: 'Simulates a subject who remains almost completely still in front of the camera, exhibiting classic ambient NPC stillness.',
  },
  looping: {
    id: 'sample-looping',
    name: 'Sample 02: The Corridor Patrol',
    tagline: 'Walks the same 3-meter line indefinitely',
    npcType: 'LOOPING NPC',
    npcLevel: 'HIGH LEVEL NPC',
    targetScore: 91,
    metrics: {
      movementRandomness: 12,
      pathRepetition: 94,
      idleBehavior: 28,
      directionChanges: 86,
      activityLevel: 68,
      movementRepetition: 93,
      predictability: 91,
      loopDetected: true,
    },
    observations: [
      'Subject repeated the exact same linear path 6 consecutive times.',
      '180-degree pivot executed with uncanny mechanical precision.',
      'Subject appears to have entered an unskippable patrol route.',
      'Zero deviation from designated imaginary corridor navmesh.',
      'Potential security guard AI routine detected.',
    ],
    mainCharacterReason: 'Path repetition exceeds 90%. Protagonists tend to jump over fences rather than patrol them.',
    description: 'Simulates a person pacing back and forth in a predictable loop, matching standard game guard pathfinding.',
  },
  protagonist: {
    id: 'sample-protagonist',
    name: 'Sample 03: The Chaos Protagonist',
    tagline: 'Erratic movement, spamming jump and spin',
    npcType: 'BACKGROUND CHARACTER',
    npcLevel: 'MAIN CHARACTER',
    targetScore: 14,
    metrics: {
      movementRandomness: 92,
      pathRepetition: 6,
      idleBehavior: 8,
      directionChanges: 91,
      activityLevel: 89,
      movementRepetition: 11,
      predictability: 12,
      loopDetected: false,
    },
    observations: [
      'Movement entropy exceeded all standard game-engine safety thresholds.',
      'Subject refused to maintain a consistent facing angle for more than 0.4s.',
      'Spontaneous erratic accelerations suggest active controller button mashing.',
      'Completely immune to background behavior optimization algorithms.',
      'System flagged subject as high-priority main character anomaly.',
    ],
    mainCharacterReason: 'Extreme movement entropy detected. Subject is actively refusing background compliance.',
    description: 'Simulates rapid, chaotic, multi-directional motion resembling a player character speedrunning or testing collision boundaries.',
  },
};
